Update docker
- formatting
- remove cgroup v1 mount
- move order from stop routine
- add start docker-watchdog to restart routine

diff --git a/etc/init.d/docker b/etc/init.d/docker
--- a/etc/init.d/docker
+++ b/etc/init.d/docker
@@ -35,43 +35,20 @@ DOCKER_DESC="Docker"
 . /lib/lsb/init-functions
 
 if [ -f /etc/default/$BASE ]; then
-	. /etc/default/$BASE
+  . /etc/default/$BASE
 fi
 
 # Check docker is present
 if [ ! -x $DOCKERD ]; then
-	log_failure_msg "$DOCKERD not present or not executable"
-	exit 1
+  log_failure_msg "$DOCKERD not present or not executable"
+  exit 1
 fi
 
 fail_unless_root() {
-	if [ "$(id -u)" != '0' ]; then
-		log_failure_msg "$DOCKER_DESC must be run as root"
-		exit 1
-	fi
-}
-
-cgroupfs_mount() {
-	# see also https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount
-	if grep -v '^#' /etc/fstab | grep -q cgroup \
-		|| [ ! -e /proc/cgroups ] \
-		|| [ ! -d /sys/fs/cgroup ]; then
-		return
-	fi
-	if ! mountpoint -q /sys/fs/cgroup; then
-		mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
-	fi
-	(
-		cd /sys/fs/cgroup
-		for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
-			mkdir -p $sys
-			if ! mountpoint -q $sys; then
-				if ! mount -n -t cgroup -o $sys cgroup $sys; then
-					rmdir $sys || true
-				fi
-			fi
-		done
-	)
+  if [ "$(id -u)" != '0' ]; then
+    log_failure_msg "$DOCKER_DESC must be run as root"
+    exit 1
+  fi
 }
 
 # MOS Custom
@@ -121,86 +98,84 @@ mos_start() {
 mos_stop() {
   umount -f /var/lib/docker 2>/dev/null
   umount -f /var/www/docker_icons 2>/dev/null
-  /etc/init.d/docker-watchdog stop 2>/dev/null
 }
 
 case "$1" in
-	start)
-		fail_unless_root
+  start)
+    fail_unless_root
 
-		# MOS custom: prevent mounting cgroup v1
-		# cgroupfs_mount
+    touch "$DOCKER_LOGFILE"
+    chgrp docker "$DOCKER_LOGFILE"
 
-		touch "$DOCKER_LOGFILE"
-		chgrp docker "$DOCKER_LOGFILE"
+    ulimit -n 1048576
 
-		ulimit -n 1048576
+    # Having non-zero limits causes performance problems due to accounting overhead
+    # in the kernel. We recommend using cgroups to do container-local accounting.
+    if [ "$BASH" ]; then
+      ulimit -u unlimited
+    else
+      ulimit -p unlimited
+    fi
 
-		# Having non-zero limits causes performance problems due to accounting overhead
-		# in the kernel. We recommend using cgroups to do container-local accounting.
-		if [ "$BASH" ]; then
-			ulimit -u unlimited
-		else
-			ulimit -p unlimited
-		fi
+    log_begin_msg "Starting $DOCKER_DESC: $BASE"
+    # MOS Custom
+    mos_start
+    start-stop-daemon --start --background \
+      --no-close \
+      --exec "$DOCKERD" \
+      --pidfile "$DOCKER_SSD_PIDFILE" \
+      --make-pidfile \
+      -- \
+      -p "$DOCKER_PIDFILE" \
+      $DOCKER_OPTS \
+      >> "$DOCKER_LOGFILE" 2>&1
+    log_end_msg $?
+    ;;
 
-		log_begin_msg "Starting $DOCKER_DESC: $BASE"
-		# MOS Custom
-		mos_start
-		start-stop-daemon --start --background \
-			--no-close \
-			--exec "$DOCKERD" \
-			--pidfile "$DOCKER_SSD_PIDFILE" \
-			--make-pidfile \
-			-- \
-			-p "$DOCKER_PIDFILE" \
-			$DOCKER_OPTS \
-			>> "$DOCKER_LOGFILE" 2>&1
-		log_end_msg $?
-		;;
+  stop)
+    fail_unless_root
+    if [ -f "$DOCKER_SSD_PIDFILE" ]; then
+      # MOS Custom
+      /etc/init.d/docker-watchdog stop 2>/dev/null
+      log_begin_msg "Stopping $DOCKER_DESC: $BASE"
+      for container in $(docker ps -q); do
+        docker stop "$container" >/dev/null 2>&1 &
+      done
+      wait
 
-	stop)
-		fail_unless_root
-		if [ -f "$DOCKER_SSD_PIDFILE" ]; then
-			# MOS Custom
-			for container in $(docker ps -q); do
-				docker stop "$container" >/dev/null 2>&1 &
-			done
-			wait
+      start-stop-daemon --stop --pidfile "$DOCKER_SSD_PIDFILE" --remove-pidfile --retry 10
+      log_end_msg $?
+      mos_stop
+    else
+      log_warning_msg "Docker already stopped - file $DOCKER_SSD_PIDFILE not found."
+    fi
+    ;;
 
-			log_begin_msg "Stopping $DOCKER_DESC: $BASE"
-			start-stop-daemon --stop --pidfile "$DOCKER_SSD_PIDFILE" --remove-pidfile --retry 10
-			log_end_msg $?
-			mos_stop
-		else
-			log_warning_msg "Docker already stopped - file $DOCKER_SSD_PIDFILE not found."
-		fi
-		;;
+  restart)
+    fail_unless_root
+    docker_pid=$(cat "$DOCKER_SSD_PIDFILE" 2> /dev/null)
+    [ -n "$docker_pid" ] \
+      && ps -p $docker_pid > /dev/null 2>&1 \
+      && $0 stop
+    $0 start
+    /etc/init.d/docker-watchdog start 2>/dev/null
+    ;;
 
-	restart)
-		fail_unless_root
-		docker_pid=$(cat "$DOCKER_SSD_PIDFILE" 2> /dev/null)
-		[ -n "$docker_pid" ] \
-			&& ps -p $docker_pid > /dev/null 2>&1 \
-			&& $0 stop
-		$0 start
-		;;
+  force-reload)
+    fail_unless_root
+    $0 restart
+    ;;
 
-	force-reload)
-		fail_unless_root
-		$0 restart
-		;;
+  status)
+    if [ -f "$DOCKER_SSD_PIDFILE" ] ; then
+      status_of_proc -p "$DOCKER_SSD_PIDFILE" "$DOCKERD" "$DOCKER_DESC"
+    else
+      echo "Docker is not running."
+    fi
+    ;;
 
-	status)
-		if [ -f "$DOCKER_SSD_PIDFILE" ] ; then
-		  status_of_proc -p "$DOCKER_SSD_PIDFILE" "$DOCKERD" "$DOCKER_DESC"
-		else
-		  echo "Docker is not running."
-		fi
-		;;
-
-	*)
-		echo "Usage: service docker {start|stop|restart|status}"
-		exit 1
-		;;
+  *)
+    echo "Usage: service docker {start|stop|restart|status}"
+    exit 1
+    ;;
 esac
